site_name: USTBAANA 北京科技大学北美校友会
site_description: USTBAANA 北京科技大学北美校友会
site_favicon: images/favicon.ico
google_analytics: ['UA-74052609-1', 'ustbaana.org']
theme: mkdocs
markdown_extensions:
  - admonition
  - def_list
  - footnotes
docs_dir: docs
pages:
  - Home: 'index.md'
  - News:
    - '芝加哥2017野餐联谊会': 'news_20170816.md'
    - '芝加哥校友会成立': 'news_20170427.md'
    - 'Website Update': 'news_20161209.md'
    - 'USTB 60th Anniversary': 'news_20120524.md'
    - 'Yonglu Zhao Seminar': 'news_20070913.md'
  - 'Special Thanks': 'news_20090618.md'
  - Links: 'links.md'
  - About Us: 'about.md'
